version: '3.10'
services:
  django:
    build: .
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - ./.env
    entrypoint:
      - ./django-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - celery
      - fastapi

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    restart: on-failure
    env_file:
      - ./.env
    ports:
#      AMQP protocol port
      - 5672:5672
#        HTTP management UI
      - 15672:15672

  celery:
    restart: always
    volumes:
      - .:/app
    build: .
    env_file:
      - ./.env
    entrypoint:
      - ./celery-entrypoint.sh
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  fastapi:
    restart: always
    volumes:
      - ./microservice:/app/microservice
    build: ./microservice
    env_file:
      - ./.env
    entrypoint:
      ./microservice/fast-api-entrypoint.sh
    depends_on:
      - rabbitmq
    ports:
      - "8001:8001"

  consumer:
    build: ./microservice
    volumes:
      - ./microservice:/app/microservice
    command:  bash -c "cd microservice && python consumer.py"
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
